
name: Main CI

on: push

jobs:
  Init_and_test:
    name: Init and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: Initialise npm
        run: npm ci

      - name: Run Jest Tests
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Set up Docker Build Tools
        uses: docker/setup-buildx-action@v3

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfiles/Test/test.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/townsend-lisa-intro-to-devops-a2:latest

        
      - name: Build user-facing image and push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfiles/User/user.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/townsend-lisa-intro-to-devops-a2:user_latest
